### ISSUE TITLE
Thanks for corrupting all profile data this app touched

### ISSUE THREAD

**Issue by HackZy01** [OfficialAhmed/Iconit-PS4#1]
This app corrupts every profile data that it has contact with, please refrain from using it till it gets fixed

**Comment by OfficialAhmed** [comment]
Could you please share any info about the issue. What happened? in what way it corrupted your profile data? screenshots? anything would help me investigate the bug further

**Comment by HackZy01** [comment]
So, after editing anything assosiated with profile: avatar change, name change
It tends to corrupt profile data which includes sign out from psn, which locks you out from playing some bought games, and changing username to "Unknown Username" and suprisingly uses default_user_440.png as it's avatar

**Comment by OfficialAhmed** [comment]
So this only for psn signed in profiles.  I will investigate and solve this issue. Thank you
