### ISSUE TITLE
Fatal error detected 

### ISSUE THREAD

**Issue by HaaMaaDa** [OfficialAhmed/Iconit-PS4#6]
I can't open iconit v4.91
error appears to me error loading python dll

![Videoframe_20221117_130658_com huawei himovie overseas](https://user-images.githubusercontent.com/118441907/202430477-7fdd2bb3-8354-45e4-b0df-543022c5e865.jpg)

**Comment by OfficialAhmed** [comment]
Make sure you have all the required files and have installed the software needed to run this tool, you need to also run as administrator and do not try to run the tool in the main drive (usually drive C:) because the main drive require extra privileges.
